### ISSUE TITLE
naming conflict with mono-devel in '/usr/bin/disco'

### ISSUE THREAD

**Issue by ZeHipo** [JOJ0/discodos#15]
when updating mono in ubuntu studio i get the error: Error while installing package: trying to overwrite '/usr/bin/disco', which is also in package discodos 1.0~rc2-2.
i don"t think this is necessarily a discodos issue, but hopefully the authors of both packages could find a solution to this.
cheers

**Comment by JOJ0** [comment]
Thanks for reporting. Actually I am not maintaining the Debian package anymore and want to focus on other packaging formats. I am not sure how I would kick it out of Debian atm. Any advice welcome 😃

**Comment by ZeHipo** [comment]
thank you for your reply @JOJ0. my plan is to submit a bug to ubuntu and hope for the best... 🫠

**Comment by JOJ0** [comment]
@ZeHipo no worries I think I can help. Did you clone the github repo or use the tarball?

**Comment by JOJ0** [comment]
@ZeHipo I don't have an Ubuntu Studio system around for testing the install as described in the discodos readthedocs page you mentioned. Can you give me some more information:

Which command excatly threw the error you posted?

What is the output of these commands:?
`python --version`
`echo $PATH`

I just tried installing systemwide on a current Manjaro (Archlinux-based) system which uses Python 3.10. This is what I did:
```
$ git clone https://github.com/JOJ0/discodos.git discodos_syswide
$ cd discodos_syswide
$ sudo python3 setup.py install
```

`which` tells me that I have another disco command already (since I use DiscoDOS from a virtual python environment). Actually a quite similar situation to yours:
```
$ which disco
/home/jojo/.pyenv/shims/disco
```

To make use of the now systemwide installed version of the `disco` command I just adjusted my path variable via .zshrc or .bashrc:

`export PATH=/usr/bin/:$PATH`

Now the proper version of disco is found:
```
$ which disco
/usr/bin/disco
```

Does that help?

And as mentioned already: I should take care of properly kicking out that very old version of DiscoDOS from Debian/Ubuntu repos. I believe that installing via git clone even is a better way. I don't have resources for maintaining a Debian package. It's quite some work involved. I might consider providing DiscoDOS as a snap or flatpak package once I get to it. In the meantime for those who want to use it on Debian, still the manual python install way is possible and shouldn't be to hard for people wanting to use a command line application I guess. I hope we can figure out why that doesn't work on your system, please help me reproduce the problem. Thanks a ton in advance! :-)

**Comment by JOJ0** [comment]
Hi @ZeHipo I got rid of the system-wide install chapter in the docs in favor of describing on how to install into the user's home. Have a look at the updated docs: https://discodos.readthedocs.io/en/latest/CONTRIBUTION.html#macos-or-linux-install-into-virtual-environment
It would be very helpful if you'd try it out on your distro to see whether it works. My resources are limited and it's not possible to test it on a varity of distros. Thanks a lot in advance again! Appreciated!

**Comment by ZeHipo** [comment]
hey, thanks for coming back to this

to clarify, on ubuntu studio discodos comes preinstalled so it is the default disco command.
since i wanted the mono environment for godot engine (which doesn't come with studio) i installed mono-devel via apt. i think most studio users would probably never install mono on their music production systems (pun not intended). so its maybe not even a problem.

the bug started when kde's "discover" package manager found an update for mono-devel which it didn't even list before i installed it, and i clicked on it. i couldn't use apt for anything else after that. it was complicated. but because of that i learned about discodos in the first place. 🤷

after fixing apt i cloned your git repo like in the tutorial. the command after cd-ing into discodos threw the error (python3 setup.py install).


`python3 --version`
`Python 3.10.4`

`echo $PATH`
`/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin`

i installed pip and venv and did the virtual environment install and discodocs runs and is recognized! i think this solution is pretty awesome. discodos running in it's own special disco shell.

the user environment tutorial didn't work for me unfortunately. at the `pip install . -e` 
it says `-e option requires 1 argument` and i just couldn't figure it out.

thanks for teaching me that virtual environment thing. python _is_ kinda cool.
